version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: handyhub
      POSTGRES_PASSWORD: handyhub
      POSTGRES_DB: handyhub
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U handyhub -d handyhub"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    ports:
      - "5000:5000"

volumes:
  pg_data:
