exports.seed = async function(knex) {
  await knex('skills').truncate();

  await knex('skills').insert([
    { name: 'Plumbing' },
    { name: 'Electrical' },
    { name: 'Painting' },
    { name: 'Cleaning' },
    { name: 'Moving' },
    { name: 'Carpentry' },
    { name: 'Gardening' },
    { name: 'Welding' },
    { name: 'Tiling' },
    { name: 'Assembly' },

    { name: 'Repair' },
    { name: 'Roofing' },
    { name: 'Flooring' },
    { name: 'Drywall' },
    { name: 'Demolition' },
    { name: 'Mounting' },
    { name: 'Delivery' },
    { name: 'Packing' },
    { name: 'Lifting' },
    { name: 'Locksmith' },

    { name: 'Concrete' },
    { name: 'Fencing' },
    { name: 'Pestcontrol' },
    { name: 'Poolcare' },
    { name: 'Decorating' },
    { name: 'Renovation' },
    { name: 'Maintenance' },
    { name: 'Transport' },
    { name: 'Networking' },
    { name: 'Cabling' },

    { name: 'Security' },
    { name: 'Automation' },
    { name: 'Landscaping' },
    { name: 'Excavation' },
    { name: 'Insulation' },
    { name: 'Soldering' },
    { name: 'Glazing' },
    { name: 'Masonry' },
    { name: 'Ventilation' },
    { name: 'Heating' },

    { name: 'Cooling' },
    { name: 'Drainage' },
    { name: 'Sanitation' },
    { name: 'Trimming' },
    { name: 'Hauling' },
    { name: 'Polishing' },
    { name: 'Laundry' },
    { name: 'Babysitting' },
    { name: 'Handyman' },
    { name: 'Cleaningup' },

    { name: 'Sweeping' },
    { name: 'Vacuuming' },
    { name: 'Mopping' },
    { name: 'Ironing' },
    { name: 'Cooking' },
    { name: 'Shopping' },
    { name: 'Tutoring' },
    { name: 'Driving' },
    { name: 'Deliveryman' },
    { name: 'Caretaking' },

    { name: 'Removals' },
    { name: 'Loading' },
    { name: 'Unloading' },
    { name: 'Digging' },
    { name: 'Planting' },
    { name: 'Pruning' },
    { name: 'Seeding' },
    { name: 'Watering' },
    { name: 'Harvesting' },
    { name: 'Cleaningcar' },

    { name: 'Detailing' },
    { name: 'Washing' },
    { name: 'Buffing' },
    { name: 'Polishingcar' },
    { name: 'Mechanics' },
    { name: 'Diagnostics' },
    { name: 'Programming' },
    { name: 'Printing' },
    { name: 'Scanning' },
    { name: 'Designing' },

    { name: 'Drafting' },
    { name: 'Modeling' },
    { name: 'Editing' },
    { name: 'Filming' },
    { name: 'Photography' },
    { name: 'Recording' },
    { name: 'Streaming' },
    { name: 'Marketing' },
    { name: 'Branding' },
    { name: 'Selling' },

    { name: 'Packingup' },
    { name: 'Organizing' },
    { name: 'Sorting' },
    { name: 'Labeling' },
    { name: 'Measuring' },
    { name: 'Cutting' },
    { name: 'Grinding' },
    { name: 'Drilling' },
    { name: 'Fastening' },
    { name: 'Bolting' }
  ]);
};